services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    network_mode: nginx-net
    external_links:
      - v2ray
    restart: always
    volumes:
      - ./:/etc/v2ray/
    # environment:
    #   - V2RAY_VMESS_AEAD_FORCED=false
