services:
  tailscaled:
    image: tailscale/tailscale:stable
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    command: tailscaled