services:
  tailscaled:
    image: tailscale/tailscale
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    command: tailscaled