services:
  derper:
    container_name: derper
    image: yangchuansheng/ip_derper
    restart: always
    ports:
      - "3478:3478/udp"
      - 12443:443
      - 12080:80
    environment:
      - DERP_ADDR=:443
      - DERP_VERIFY_CLIENTS=false
      - DERP_HTTP_PORT=80