services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    restart: always
    command: redis-server --requirepass password
    ports:
      - 6379:6379
    volumes:
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
