services:
  npc:
    build:
      context: .
      dockerfile: Dockerfile
    image: npc:1.0.1
    container_name: npc
    restart: always
    init: true  # 修复 setpgid 问题
    network_mode: host  # 使用宿主机网络
    volumes:
      - ./app:/app
#      - ./logs:/var/log/cron
    environment:
      TZ: Asia/Shanghai
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "pgrep crond || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks: {}